routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Pages Routes

Route::get('/', 'PagesController@index');
Route::get('/terms','PagesController@terms');
Route::get('/contact','PagesController@contact');
Route::get('/about','PagesController@about');
Route::get('/faq','PagesController@faq');
Route::get('/news','PagesController@news');
Route::get('/privacy','PagesController@privacy');
Route::get('/bibliography','PagesController@bibliography');

//User Authentication Routes
Auth::routes();

//Video controller routes
Route::resource('videos', 'VideosController');

//Home Route
Route::get('/home', 'HomeController@index')->name('home');

//Replies Routes
Route::get('/videos/{subject}/{video}/replies', 'RepliesController@index');
Route::get('/videos/{subject}/{video}/reply', 'RepliesController@create');
Route::resource('replies', 'RepliesController');

//Subjects routes
Route::resource('subjects', 'SubjectController');

app/Reply.php
<?php
// Model responsible for taking user reply input data into the database and retrieves user replies
namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Purify;

class Reply extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];
    // Table Name
    protected $table = 'replies';
    // Primary Key
    public $primaryKey = 'id';
    // Timestamps
    public $timestamps = true;

    protected $fillable=['user_id', 'video_id', 'parent_id', 'body'];

    /**
     * A reply has an owner.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * A reply belongs to a video.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function video()
    {
        return $this->belongsTo(Video::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class, 'parent_id');
    }

    public function path()
    {
        return $this->thread->path() . "#reply-{$this->id}";
    }
}

app/Http/Controllers/RepliesController.php
<?php

namespace App\Http\Controllers;

use App\Reply;
use App\Subject;
use App\Video;
use Illuminate\Http\Request;

class RepliesController extends Controller
{
    /**
     * Persist a new reply.
     *
     * @return \Illuminate\Database\Eloquent\Model
     * Function stores the replies to the database and redirect user back to the video post
     */
    public function store(Request $request)
    {
        request()->validate([
            'body' => 'required'
        ]);
        $input = $request->all();
        $input['user_id'] = auth()->user()->id;
        Reply::create($input);

        return back();
    }

    /**
     * Function Update an existing reply.
     *
     * @param Reply $reply
     */
    public function update(Reply $reply)
    {
        $this->authorize('update', $reply);

        $reply->update(request()->validate(['body' => 'required']));
    }

    /**
     * Function Deletes the given reply.
     *
     * @param  Reply $reply
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Reply $reply)
    {
        $this->authorize('update', $reply);
        $reply->delete();
        if (request()->expectsJson()) {
            return response(['status' => 'Reply deleted']);
        }
        return back();
    }
}

resources/views/replies/reply_form.blade.php
@foreach($replies as $reply)
    <div class="display-comment" @if($reply->parent_id != null) style="margin-left:40px;" @endif>
        <strong>{{ $reply->user->name }}</strong>
        <p>{{ $reply->body }}</p>
        <a href="" id="reply"></a>
        <form method="post" action="{{ route('replies.store') }}">
            @csrf
            <div class="form-group">
                <input type="text" name="body" class="form-control" />
                <input type="hidden" name="video_id" value="{{ $video_id }}" />
                <input type="hidden" name="parent_id" value="{{ $reply->id }}" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-warning" value="Reply" />
            </div>
        </form>
        @include('videos.repliesDisplay', ['replies' => $reply->replies])
    </div>
@endforeach

resources/views/replies/reply_thread.blade.php
<reply :attributes="{{ $reply }}" inline-template v-cloak>
    <div id="reply-{{ $reply->id }}" class="panel panel-default">
        <div class="panel-heading">
            <div class="level">
                <h5 class="flex">
                    <a href="{{ route('/home', $reply->owner) }}">
                        {{ $reply->owner->name }}
                    </a> said {{ $reply->created_at->diffForHumans() }}...
                </h5>

                @if (Auth::check())
                    <div>
                        <favorite :reply="{{ $reply }}"></favorite>
                    </div>
                @endif
            </div>
        </div>

        <div class="panel-body">
            <div v-if="editing">
                <div class="form-group">
                    <textarea class="form-control" v-model="body"></textarea>
                </div>

                <button class="btn btn-xs btn-primary" @click="update">Update</button>
                <button class="btn btn-xs btn-link" @click="editing = false">Cancel</button>
            </div>

            <div v-else v-text="body"></div>
        </div>

        @can ('update', $reply)
            <div class="panel-footer level">
                <button class="btn btn-xs mr-1" @click="editing = true">Edit</button>
                <button class="btn btn-xs btn-danger mr-1" @click="destroy">Delete</button>
            </div>
        @endcan
    </div>
</reply>